/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanaryRouteImport } from './routes/canary'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as MusicRouteImport } from './routes/music'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as Tier1RouteImport } from './routes/tier1'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as AgentMerchRouteImport } from './routes/agent.merch'
import { Route as ApiPrintifySubscriptionsRouteImport } from './routes/api/printify/subscriptions'
import { Route as ApiPrintifyWebhooksRouteImport } from './routes/api/printify/webhooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaryRoute = CanaryRouteImport.update({
  id: '/canary',
  path: '/canary',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const Tier1Route = Tier1RouteImport.update({
  id: '/tier1',
  path: '/tier1',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMerchRoute = AgentMerchRouteImport.update({
  id: '/agent/merch',
  path: '/agent/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrintifySubscriptionsRoute =
  ApiPrintifySubscriptionsRouteImport.update({
    id: '/api/printify/subscriptions',
    path: '/api/printify/subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrintifyWebhooksRoute = ApiPrintifyWebhooksRouteImport.update({
  id: '/api/printify/webhooks',
  path: '/api/printify/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canary': typeof CanaryRoute
  '/merch': typeof MerchRoute
  '/music': typeof MusicRoute
  '/pay': typeof PayRoute
  '/pipeline': typeof PipelineRoute
  '/queue': typeof QueueRoute
  '/skills': typeof SkillsRoute
  '/tier1': typeof Tier1Route
  '/webhooks': typeof WebhooksRoute
  '/agent/merch': typeof AgentMerchRoute
  '/api/printify/subscriptions': typeof ApiPrintifySubscriptionsRoute
  '/api/printify/webhooks': typeof ApiPrintifyWebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canary': typeof CanaryRoute
  '/merch': typeof MerchRoute
  '/music': typeof MusicRoute
  '/pay': typeof PayRoute
  '/pipeline': typeof PipelineRoute
  '/queue': typeof QueueRoute
  '/skills': typeof SkillsRoute
  '/tier1': typeof Tier1Route
  '/webhooks': typeof WebhooksRoute
  '/agent/merch': typeof AgentMerchRoute
  '/api/printify/subscriptions': typeof ApiPrintifySubscriptionsRoute
  '/api/printify/webhooks': typeof ApiPrintifyWebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canary': typeof CanaryRoute
  '/merch': typeof MerchRoute
  '/music': typeof MusicRoute
  '/pay': typeof PayRoute
  '/pipeline': typeof PipelineRoute
  '/queue': typeof QueueRoute
  '/skills': typeof SkillsRoute
  '/tier1': typeof Tier1Route
  '/webhooks': typeof WebhooksRoute
  '/agent/merch': typeof AgentMerchRoute
  '/api/printify/subscriptions': typeof ApiPrintifySubscriptionsRoute
  '/api/printify/webhooks': typeof ApiPrintifyWebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canary'
    | '/merch'
    | '/music'
    | '/pay'
    | '/pipeline'
    | '/queue'
    | '/skills'
    | '/tier1'
    | '/webhooks'
    | '/agent/merch'
    | '/api/printify/subscriptions'
    | '/api/printify/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canary'
    | '/merch'
    | '/music'
    | '/pay'
    | '/pipeline'
    | '/queue'
    | '/skills'
    | '/tier1'
    | '/webhooks'
    | '/agent/merch'
    | '/api/printify/subscriptions'
    | '/api/printify/webhooks'
  id:
    | '__root__'
    | '/'
    | '/canary'
    | '/merch'
    | '/music'
    | '/pay'
    | '/pipeline'
    | '/queue'
    | '/skills'
    | '/tier1'
    | '/webhooks'
    | '/agent/merch'
    | '/api/printify/subscriptions'
    | '/api/printify/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanaryRoute: typeof CanaryRoute
  MerchRoute: typeof MerchRoute
  MusicRoute: typeof MusicRoute
  PayRoute: typeof PayRoute
  PipelineRoute: typeof PipelineRoute
  QueueRoute: typeof QueueRoute
  SkillsRoute: typeof SkillsRoute
  Tier1Route: typeof Tier1Route
  WebhooksRoute: typeof WebhooksRoute
  AgentMerchRoute: typeof AgentMerchRoute
  ApiPrintifySubscriptionsRoute: typeof ApiPrintifySubscriptionsRoute
  ApiPrintifyWebhooksRoute: typeof ApiPrintifyWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canary': {
      id: '/canary'
      path: '/canary'
      fullPath: '/canary'
      preLoaderRoute: typeof CanaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier1': {
      id: '/tier1'
      path: '/tier1'
      fullPath: '/tier1'
      preLoaderRoute: typeof Tier1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/merch': {
      id: '/agent/merch'
      path: '/agent/merch'
      fullPath: '/agent/merch'
      preLoaderRoute: typeof AgentMerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/printify/subscriptions': {
      id: '/api/printify/subscriptions'
      path: '/api/printify/subscriptions'
      fullPath: '/api/printify/subscriptions'
      preLoaderRoute: typeof ApiPrintifySubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/printify/webhooks': {
      id: '/api/printify/webhooks'
      path: '/api/printify/webhooks'
      fullPath: '/api/printify/webhooks'
      preLoaderRoute: typeof ApiPrintifyWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanaryRoute: CanaryRoute,
  MerchRoute: MerchRoute,
  MusicRoute: MusicRoute,
  PayRoute: PayRoute,
  PipelineRoute: PipelineRoute,
  QueueRoute: QueueRoute,
  SkillsRoute: SkillsRoute,
  Tier1Route: Tier1Route,
  WebhooksRoute: WebhooksRoute,
  AgentMerchRoute: AgentMerchRoute,
  ApiPrintifySubscriptionsRoute: ApiPrintifySubscriptionsRoute,
  ApiPrintifyWebhooksRoute: ApiPrintifyWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
