/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AnchorRouteImport } from './routes/anchor'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as BountyRouteImport } from './routes/bounty'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as CanaryRouteImport } from './routes/canary'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CircuitRouteImport } from './routes/circuit'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as GuildRouteImport } from './routes/guild'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as MirrorRouteImport } from './routes/mirror'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as MusicRouteImport } from './routes/music'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as RelayRouteImport } from './routes/relay'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as ShopRouteRouteImport } from './routes/shop/route'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SyndicateRouteImport } from './routes/syndicate'
import { Route as Tier1RouteImport } from './routes/tier1'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as WhisperRouteImport } from './routes/whisper'
import { Route as AgentMerchRouteImport } from './routes/agent.merch'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopSearchRouteImport } from './routes/shop/search'
import { Route as ShopWishlistRouteImport } from './routes/shop/wishlist'
import { Route as WellKnownAgentDotjsonRouteImport } from './routes/well-known/agent[.]json'
import { Route as ApiAgentCardRouteImport } from './routes/api/agent/card'
import { Route as ApiAgentOrdersRouteImport } from './routes/api/agent/orders'
import { Route as ApiAgentQuoteRouteImport } from './routes/api/agent/quote'
import { Route as ApiAwsStatusRouteImport } from './routes/api/aws/status'
import { Route as ApiPayOptionsRouteImport } from './routes/api/pay/options'
import { Route as ApiPrintifySubscriptionsRouteImport } from './routes/api/printify/subscriptions'
import { Route as ApiPrintifySyncRouteImport } from './routes/api/printify/sync'
import { Route as ApiPrintifyWebhooksRouteImport } from './routes/api/printify/webhooks'
import { Route as ApiStoreCatalogRouteImport } from './routes/api/store/catalog'
import { Route as ApiStoreImageRouteImport } from './routes/api/store/image'
import { Route as ShopCollectionsHandleRouteImport } from './routes/shop/collections.$handle'
import { Route as ApiAgentOrdersIdRouteImport } from './routes/api/agent/orders.$id'
import { Route as ApiAgentOrdersIdPayRouteImport } from './routes/api/agent/orders.$id.pay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AnchorRoute = AnchorRouteImport.update({
  id: '/anchor',
  path: '/anchor',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const BountyRoute = BountyRouteImport.update({
  id: '/bounty',
  path: '/bounty',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaryRoute = CanaryRouteImport.update({
  id: '/canary',
  path: '/canary',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitRoute = CircuitRouteImport.update({
  id: '/circuit',
  path: '/circuit',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildRoute = GuildRouteImport.update({
  id: '/guild',
  path: '/guild',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorRoute = MirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayRoute = RelayRouteImport.update({
  id: '/relay',
  path: '/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicateRoute = SyndicateRouteImport.update({
  id: '/syndicate',
  path: '/syndicate',
  getParentRoute: () => rootRouteImport,
} as any)
const Tier1Route = Tier1RouteImport.update({
  id: '/tier1',
  path: '/tier1',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const WhisperRoute = WhisperRouteImport.update({
  id: '/whisper',
  path: '/whisper',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMerchRoute = AgentMerchRouteImport.update({
  id: '/agent/merch',
  path: '/agent/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopWishlistRoute = ShopWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ShopRouteRoute,
} as any)
const WellKnownAgentDotjsonRoute = WellKnownAgentDotjsonRouteImport.update({
  id: '/well-known/agent.json',
  path: '/well-known/agent.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentCardRoute = ApiAgentCardRouteImport.update({
  id: '/api/agent/card',
  path: '/api/agent/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentOrdersRoute = ApiAgentOrdersRouteImport.update({
  id: '/api/agent/orders',
  path: '/api/agent/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentQuoteRoute = ApiAgentQuoteRouteImport.update({
  id: '/api/agent/quote',
  path: '/api/agent/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAwsStatusRoute = ApiAwsStatusRouteImport.update({
  id: '/api/aws/status',
  path: '/api/aws/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayOptionsRoute = ApiPayOptionsRouteImport.update({
  id: '/api/pay/options',
  path: '/api/pay/options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrintifySubscriptionsRoute =
  ApiPrintifySubscriptionsRouteImport.update({
    id: '/api/printify/subscriptions',
    path: '/api/printify/subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrintifySyncRoute = ApiPrintifySyncRouteImport.update({
  id: '/api/printify/sync',
  path: '/api/printify/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrintifyWebhooksRoute = ApiPrintifyWebhooksRouteImport.update({
  id: '/api/printify/webhooks',
  path: '/api/printify/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreCatalogRoute = ApiStoreCatalogRouteImport.update({
  id: '/api/store/catalog',
  path: '/api/store/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreImageRoute = ApiStoreImageRouteImport.update({
  id: '/api/store/image',
  path: '/api/store/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCollectionsHandleRoute = ShopCollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ApiAgentOrdersIdRoute = ApiAgentOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAgentOrdersRoute,
} as any)
const ApiAgentOrdersIdPayRoute = ApiAgentOrdersIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => ApiAgentOrdersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop': typeof ShopRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/anchor': typeof AnchorRoute
  '/arena': typeof ArenaRoute
  '/bounty': typeof BountyRoute
  '/bundles': typeof BundlesRoute
  '/canary': typeof CanaryRoute
  '/checkout': typeof CheckoutRoute
  '/circuit': typeof CircuitRoute
  '/drops': typeof DropsRoute
  '/exchange': typeof ExchangeRoute
  '/fleet': typeof FleetRoute
  '/forge': typeof ForgeRoute
  '/guild': typeof GuildRoute
  '/labs': typeof LabsRoute
  '/launch': typeof LaunchRoute
  '/ledger': typeof LedgerRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/marketplace': typeof MarketplaceRoute
  '/merch': typeof MerchRoute
  '/mirror': typeof MirrorRoute
  '/monitor': typeof MonitorRoute
  '/music': typeof MusicRoute
  '/network': typeof NetworkRoute
  '/oracle': typeof OracleRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pay': typeof PayRoute
  '/pipeline': typeof PipelineRoute
  '/pulse': typeof PulseRoute
  '/quest': typeof QuestRoute
  '/queue': typeof QueueRoute
  '/radar': typeof RadarRoute
  '/relay': typeof RelayRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seller': typeof SellerRoute
  '/signal': typeof SignalRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRoute
  '/syndicate': typeof SyndicateRoute
  '/tier1': typeof Tier1Route
  '/vault': typeof VaultRoute
  '/webhooks': typeof WebhooksRoute
  '/whisper': typeof WhisperRoute
  '/agent/merch': typeof AgentMerchRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/orders/$id': typeof OrdersIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/wishlist': typeof ShopWishlistRoute
  '/well-known/agent.json': typeof WellKnownAgentDotjsonRoute
  '/shop/': typeof ShopIndexRoute
  '/api/agent/card': typeof ApiAgentCardRoute
  '/api/agent/orders': typeof ApiAgentOrdersRouteWithChildren
  '/api/agent/quote': typeof ApiAgentQuoteRoute
  '/api/aws/status': typeof ApiAwsStatusRoute
  '/api/pay/options': typeof ApiPayOptionsRoute
  '/api/printify/subscriptions': typeof ApiPrintifySubscriptionsRoute
  '/api/printify/sync': typeof ApiPrintifySyncRoute
  '/api/printify/webhooks': typeof ApiPrintifyWebhooksRoute
  '/api/store/catalog': typeof ApiStoreCatalogRoute
  '/api/store/image': typeof ApiStoreImageRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/api/agent/orders/$id': typeof ApiAgentOrdersIdRouteWithChildren
  '/api/agent/orders/$id/pay': typeof ApiAgentOrdersIdPayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/anchor': typeof AnchorRoute
  '/arena': typeof ArenaRoute
  '/bounty': typeof BountyRoute
  '/bundles': typeof BundlesRoute
  '/canary': typeof CanaryRoute
  '/checkout': typeof CheckoutRoute
  '/circuit': typeof CircuitRoute
  '/drops': typeof DropsRoute
  '/exchange': typeof ExchangeRoute
  '/fleet': typeof FleetRoute
  '/forge': typeof ForgeRoute
  '/guild': typeof GuildRoute
  '/labs': typeof LabsRoute
  '/launch': typeof LaunchRoute
  '/ledger': typeof LedgerRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/marketplace': typeof MarketplaceRoute
  '/merch': typeof MerchRoute
  '/mirror': typeof MirrorRoute
  '/monitor': typeof MonitorRoute
  '/music': typeof MusicRoute
  '/network': typeof NetworkRoute
  '/oracle': typeof OracleRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pay': typeof PayRoute
  '/pipeline': typeof PipelineRoute
  '/pulse': typeof PulseRoute
  '/quest': typeof QuestRoute
  '/queue': typeof QueueRoute
  '/radar': typeof RadarRoute
  '/relay': typeof RelayRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seller': typeof SellerRoute
  '/signal': typeof SignalRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRoute
  '/syndicate': typeof SyndicateRoute
  '/tier1': typeof Tier1Route
  '/vault': typeof VaultRoute
  '/webhooks': typeof WebhooksRoute
  '/whisper': typeof WhisperRoute
  '/agent/merch': typeof AgentMerchRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/orders/$id': typeof OrdersIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/wishlist': typeof ShopWishlistRoute
  '/well-known/agent.json': typeof WellKnownAgentDotjsonRoute
  '/shop': typeof ShopIndexRoute
  '/api/agent/card': typeof ApiAgentCardRoute
  '/api/agent/orders': typeof ApiAgentOrdersRouteWithChildren
  '/api/agent/quote': typeof ApiAgentQuoteRoute
  '/api/aws/status': typeof ApiAwsStatusRoute
  '/api/pay/options': typeof ApiPayOptionsRoute
  '/api/printify/subscriptions': typeof ApiPrintifySubscriptionsRoute
  '/api/printify/sync': typeof ApiPrintifySyncRoute
  '/api/printify/webhooks': typeof ApiPrintifyWebhooksRoute
  '/api/store/catalog': typeof ApiStoreCatalogRoute
  '/api/store/image': typeof ApiStoreImageRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/api/agent/orders/$id': typeof ApiAgentOrdersIdRouteWithChildren
  '/api/agent/orders/$id/pay': typeof ApiAgentOrdersIdPayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop': typeof ShopRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/anchor': typeof AnchorRoute
  '/arena': typeof ArenaRoute
  '/bounty': typeof BountyRoute
  '/bundles': typeof BundlesRoute
  '/canary': typeof CanaryRoute
  '/checkout': typeof CheckoutRoute
  '/circuit': typeof CircuitRoute
  '/drops': typeof DropsRoute
  '/exchange': typeof ExchangeRoute
  '/fleet': typeof FleetRoute
  '/forge': typeof ForgeRoute
  '/guild': typeof GuildRoute
  '/labs': typeof LabsRoute
  '/launch': typeof LaunchRoute
  '/ledger': typeof LedgerRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/marketplace': typeof MarketplaceRoute
  '/merch': typeof MerchRoute
  '/mirror': typeof MirrorRoute
  '/monitor': typeof MonitorRoute
  '/music': typeof MusicRoute
  '/network': typeof NetworkRoute
  '/oracle': typeof OracleRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pay': typeof PayRoute
  '/pipeline': typeof PipelineRoute
  '/pulse': typeof PulseRoute
  '/quest': typeof QuestRoute
  '/queue': typeof QueueRoute
  '/radar': typeof RadarRoute
  '/relay': typeof RelayRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seller': typeof SellerRoute
  '/signal': typeof SignalRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRoute
  '/syndicate': typeof SyndicateRoute
  '/tier1': typeof Tier1Route
  '/vault': typeof VaultRoute
  '/webhooks': typeof WebhooksRoute
  '/whisper': typeof WhisperRoute
  '/agent/merch': typeof AgentMerchRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/orders/$id': typeof OrdersIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/wishlist': typeof ShopWishlistRoute
  '/well-known/agent.json': typeof WellKnownAgentDotjsonRoute
  '/shop/': typeof ShopIndexRoute
  '/api/agent/card': typeof ApiAgentCardRoute
  '/api/agent/orders': typeof ApiAgentOrdersRouteWithChildren
  '/api/agent/quote': typeof ApiAgentQuoteRoute
  '/api/aws/status': typeof ApiAwsStatusRoute
  '/api/pay/options': typeof ApiPayOptionsRoute
  '/api/printify/subscriptions': typeof ApiPrintifySubscriptionsRoute
  '/api/printify/sync': typeof ApiPrintifySyncRoute
  '/api/printify/webhooks': typeof ApiPrintifyWebhooksRoute
  '/api/store/catalog': typeof ApiStoreCatalogRoute
  '/api/store/image': typeof ApiStoreImageRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/api/agent/orders/$id': typeof ApiAgentOrdersIdRouteWithChildren
  '/api/agent/orders/$id/pay': typeof ApiAgentOrdersIdPayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop'
    | '/account'
    | '/anchor'
    | '/arena'
    | '/bounty'
    | '/bundles'
    | '/canary'
    | '/checkout'
    | '/circuit'
    | '/drops'
    | '/exchange'
    | '/fleet'
    | '/forge'
    | '/guild'
    | '/labs'
    | '/launch'
    | '/ledger'
    | '/llms.txt'
    | '/marketplace'
    | '/merch'
    | '/mirror'
    | '/monitor'
    | '/music'
    | '/network'
    | '/oracle'
    | '/orders'
    | '/pay'
    | '/pipeline'
    | '/pulse'
    | '/quest'
    | '/queue'
    | '/radar'
    | '/relay'
    | '/robots.txt'
    | '/seller'
    | '/signal'
    | '/skills'
    | '/studio'
    | '/syndicate'
    | '/tier1'
    | '/vault'
    | '/webhooks'
    | '/whisper'
    | '/agent/merch'
    | '/api/openapi.json'
    | '/orders/$id'
    | '/shop/$slug'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/wishlist'
    | '/well-known/agent.json'
    | '/shop/'
    | '/api/agent/card'
    | '/api/agent/orders'
    | '/api/agent/quote'
    | '/api/aws/status'
    | '/api/pay/options'
    | '/api/printify/subscriptions'
    | '/api/printify/sync'
    | '/api/printify/webhooks'
    | '/api/store/catalog'
    | '/api/store/image'
    | '/shop/collections/$handle'
    | '/api/agent/orders/$id'
    | '/api/agent/orders/$id/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/anchor'
    | '/arena'
    | '/bounty'
    | '/bundles'
    | '/canary'
    | '/checkout'
    | '/circuit'
    | '/drops'
    | '/exchange'
    | '/fleet'
    | '/forge'
    | '/guild'
    | '/labs'
    | '/launch'
    | '/ledger'
    | '/llms.txt'
    | '/marketplace'
    | '/merch'
    | '/mirror'
    | '/monitor'
    | '/music'
    | '/network'
    | '/oracle'
    | '/orders'
    | '/pay'
    | '/pipeline'
    | '/pulse'
    | '/quest'
    | '/queue'
    | '/radar'
    | '/relay'
    | '/robots.txt'
    | '/seller'
    | '/signal'
    | '/skills'
    | '/studio'
    | '/syndicate'
    | '/tier1'
    | '/vault'
    | '/webhooks'
    | '/whisper'
    | '/agent/merch'
    | '/api/openapi.json'
    | '/orders/$id'
    | '/shop/$slug'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/wishlist'
    | '/well-known/agent.json'
    | '/shop'
    | '/api/agent/card'
    | '/api/agent/orders'
    | '/api/agent/quote'
    | '/api/aws/status'
    | '/api/pay/options'
    | '/api/printify/subscriptions'
    | '/api/printify/sync'
    | '/api/printify/webhooks'
    | '/api/store/catalog'
    | '/api/store/image'
    | '/shop/collections/$handle'
    | '/api/agent/orders/$id'
    | '/api/agent/orders/$id/pay'
  id:
    | '__root__'
    | '/'
    | '/shop'
    | '/account'
    | '/anchor'
    | '/arena'
    | '/bounty'
    | '/bundles'
    | '/canary'
    | '/checkout'
    | '/circuit'
    | '/drops'
    | '/exchange'
    | '/fleet'
    | '/forge'
    | '/guild'
    | '/labs'
    | '/launch'
    | '/ledger'
    | '/llms.txt'
    | '/marketplace'
    | '/merch'
    | '/mirror'
    | '/monitor'
    | '/music'
    | '/network'
    | '/oracle'
    | '/orders'
    | '/pay'
    | '/pipeline'
    | '/pulse'
    | '/quest'
    | '/queue'
    | '/radar'
    | '/relay'
    | '/robots.txt'
    | '/seller'
    | '/signal'
    | '/skills'
    | '/studio'
    | '/syndicate'
    | '/tier1'
    | '/vault'
    | '/webhooks'
    | '/whisper'
    | '/agent/merch'
    | '/api/openapi.json'
    | '/orders/$id'
    | '/shop/$slug'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/wishlist'
    | '/well-known/agent.json'
    | '/shop/'
    | '/api/agent/card'
    | '/api/agent/orders'
    | '/api/agent/quote'
    | '/api/aws/status'
    | '/api/pay/options'
    | '/api/printify/subscriptions'
    | '/api/printify/sync'
    | '/api/printify/webhooks'
    | '/api/store/catalog'
    | '/api/store/image'
    | '/shop/collections/$handle'
    | '/api/agent/orders/$id'
    | '/api/agent/orders/$id/pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AnchorRoute: typeof AnchorRoute
  ArenaRoute: typeof ArenaRoute
  BountyRoute: typeof BountyRoute
  BundlesRoute: typeof BundlesRoute
  CanaryRoute: typeof CanaryRoute
  CheckoutRoute: typeof CheckoutRoute
  CircuitRoute: typeof CircuitRoute
  DropsRoute: typeof DropsRoute
  ExchangeRoute: typeof ExchangeRoute
  FleetRoute: typeof FleetRoute
  ForgeRoute: typeof ForgeRoute
  GuildRoute: typeof GuildRoute
  LabsRoute: typeof LabsRoute
  LaunchRoute: typeof LaunchRoute
  LedgerRoute: typeof LedgerRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MerchRoute: typeof MerchRoute
  MirrorRoute: typeof MirrorRoute
  MonitorRoute: typeof MonitorRoute
  MusicRoute: typeof MusicRoute
  NetworkRoute: typeof NetworkRoute
  OracleRoute: typeof OracleRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PayRoute: typeof PayRoute
  PipelineRoute: typeof PipelineRoute
  PulseRoute: typeof PulseRoute
  QuestRoute: typeof QuestRoute
  QueueRoute: typeof QueueRoute
  RadarRoute: typeof RadarRoute
  RelayRoute: typeof RelayRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SellerRoute: typeof SellerRoute
  SignalRoute: typeof SignalRoute
  SkillsRoute: typeof SkillsRoute
  StudioRoute: typeof StudioRoute
  SyndicateRoute: typeof SyndicateRoute
  Tier1Route: typeof Tier1Route
  VaultRoute: typeof VaultRoute
  WebhooksRoute: typeof WebhooksRoute
  WhisperRoute: typeof WhisperRoute
  AgentMerchRoute: typeof AgentMerchRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  WellKnownAgentDotjsonRoute: typeof WellKnownAgentDotjsonRoute
  ApiAgentCardRoute: typeof ApiAgentCardRoute
  ApiAgentOrdersRoute: typeof ApiAgentOrdersRouteWithChildren
  ApiAgentQuoteRoute: typeof ApiAgentQuoteRoute
  ApiAwsStatusRoute: typeof ApiAwsStatusRoute
  ApiPayOptionsRoute: typeof ApiPayOptionsRoute
  ApiPrintifySubscriptionsRoute: typeof ApiPrintifySubscriptionsRoute
  ApiPrintifySyncRoute: typeof ApiPrintifySyncRoute
  ApiPrintifyWebhooksRoute: typeof ApiPrintifyWebhooksRoute
  ApiStoreCatalogRoute: typeof ApiStoreCatalogRoute
  ApiStoreImageRoute: typeof ApiStoreImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anchor': {
      id: '/anchor'
      path: '/anchor'
      fullPath: '/anchor'
      preLoaderRoute: typeof AnchorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounty': {
      id: '/bounty'
      path: '/bounty'
      fullPath: '/bounty'
      preLoaderRoute: typeof BountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canary': {
      id: '/canary'
      path: '/canary'
      fullPath: '/canary'
      preLoaderRoute: typeof CanaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuit': {
      id: '/circuit'
      path: '/circuit'
      fullPath: '/circuit'
      preLoaderRoute: typeof CircuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild': {
      id: '/guild'
      path: '/guild'
      fullPath: '/guild'
      preLoaderRoute: typeof GuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirror': {
      id: '/mirror'
      path: '/mirror'
      fullPath: '/mirror'
      preLoaderRoute: typeof MirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relay': {
      id: '/relay'
      path: '/relay'
      fullPath: '/relay'
      preLoaderRoute: typeof RelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicate': {
      id: '/syndicate'
      path: '/syndicate'
      fullPath: '/syndicate'
      preLoaderRoute: typeof SyndicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier1': {
      id: '/tier1'
      path: '/tier1'
      fullPath: '/tier1'
      preLoaderRoute: typeof Tier1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whisper': {
      id: '/whisper'
      path: '/whisper'
      fullPath: '/whisper'
      preLoaderRoute: typeof WhisperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/merch': {
      id: '/agent/merch'
      path: '/agent/merch'
      fullPath: '/agent/merch'
      preLoaderRoute: typeof AgentMerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/shop/search': {
      id: '/shop/search'
      path: '/search'
      fullPath: '/shop/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/shop/wishlist': {
      id: '/shop/wishlist'
      path: '/wishlist'
      fullPath: '/shop/wishlist'
      preLoaderRoute: typeof ShopWishlistRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/well-known/agent.json': {
      id: '/well-known/agent.json'
      path: '/well-known/agent.json'
      fullPath: '/well-known/agent.json'
      preLoaderRoute: typeof WellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/card': {
      id: '/api/agent/card'
      path: '/api/agent/card'
      fullPath: '/api/agent/card'
      preLoaderRoute: typeof ApiAgentCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/orders': {
      id: '/api/agent/orders'
      path: '/api/agent/orders'
      fullPath: '/api/agent/orders'
      preLoaderRoute: typeof ApiAgentOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/quote': {
      id: '/api/agent/quote'
      path: '/api/agent/quote'
      fullPath: '/api/agent/quote'
      preLoaderRoute: typeof ApiAgentQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aws/status': {
      id: '/api/aws/status'
      path: '/api/aws/status'
      fullPath: '/api/aws/status'
      preLoaderRoute: typeof ApiAwsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pay/options': {
      id: '/api/pay/options'
      path: '/api/pay/options'
      fullPath: '/api/pay/options'
      preLoaderRoute: typeof ApiPayOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/printify/subscriptions': {
      id: '/api/printify/subscriptions'
      path: '/api/printify/subscriptions'
      fullPath: '/api/printify/subscriptions'
      preLoaderRoute: typeof ApiPrintifySubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/printify/sync': {
      id: '/api/printify/sync'
      path: '/api/printify/sync'
      fullPath: '/api/printify/sync'
      preLoaderRoute: typeof ApiPrintifySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/printify/webhooks': {
      id: '/api/printify/webhooks'
      path: '/api/printify/webhooks'
      fullPath: '/api/printify/webhooks'
      preLoaderRoute: typeof ApiPrintifyWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/catalog': {
      id: '/api/store/catalog'
      path: '/api/store/catalog'
      fullPath: '/api/store/catalog'
      preLoaderRoute: typeof ApiStoreCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/image': {
      id: '/api/store/image'
      path: '/api/store/image'
      fullPath: '/api/store/image'
      preLoaderRoute: typeof ApiStoreImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/collections/$handle': {
      id: '/shop/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/shop/collections/$handle'
      preLoaderRoute: typeof ShopCollectionsHandleRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/api/agent/orders/$id': {
      id: '/api/agent/orders/$id'
      path: '/$id'
      fullPath: '/api/agent/orders/$id'
      preLoaderRoute: typeof ApiAgentOrdersIdRouteImport
      parentRoute: typeof ApiAgentOrdersRoute
    }
    '/api/agent/orders/$id/pay': {
      id: '/api/agent/orders/$id/pay'
      path: '/pay'
      fullPath: '/api/agent/orders/$id/pay'
      preLoaderRoute: typeof ApiAgentOrdersIdPayRouteImport
      parentRoute: typeof ApiAgentOrdersIdRoute
    }
  }
}

interface ShopRouteRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopWishlistRoute: typeof ShopWishlistRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionsHandleRoute: typeof ShopCollectionsHandleRoute
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopCartRoute: ShopCartRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopWishlistRoute: ShopWishlistRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionsHandleRoute: ShopCollectionsHandleRoute,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ApiAgentOrdersIdRouteChildren {
  ApiAgentOrdersIdPayRoute: typeof ApiAgentOrdersIdPayRoute
}

const ApiAgentOrdersIdRouteChildren: ApiAgentOrdersIdRouteChildren = {
  ApiAgentOrdersIdPayRoute: ApiAgentOrdersIdPayRoute,
}

const ApiAgentOrdersIdRouteWithChildren =
  ApiAgentOrdersIdRoute._addFileChildren(ApiAgentOrdersIdRouteChildren)

interface ApiAgentOrdersRouteChildren {
  ApiAgentOrdersIdRoute: typeof ApiAgentOrdersIdRouteWithChildren
}

const ApiAgentOrdersRouteChildren: ApiAgentOrdersRouteChildren = {
  ApiAgentOrdersIdRoute: ApiAgentOrdersIdRouteWithChildren,
}

const ApiAgentOrdersRouteWithChildren = ApiAgentOrdersRoute._addFileChildren(
  ApiAgentOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopRouteRoute: ShopRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AnchorRoute: AnchorRoute,
  ArenaRoute: ArenaRoute,
  BountyRoute: BountyRoute,
  BundlesRoute: BundlesRoute,
  CanaryRoute: CanaryRoute,
  CheckoutRoute: CheckoutRoute,
  CircuitRoute: CircuitRoute,
  DropsRoute: DropsRoute,
  ExchangeRoute: ExchangeRoute,
  FleetRoute: FleetRoute,
  ForgeRoute: ForgeRoute,
  GuildRoute: GuildRoute,
  LabsRoute: LabsRoute,
  LaunchRoute: LaunchRoute,
  LedgerRoute: LedgerRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MarketplaceRoute: MarketplaceRoute,
  MerchRoute: MerchRoute,
  MirrorRoute: MirrorRoute,
  MonitorRoute: MonitorRoute,
  MusicRoute: MusicRoute,
  NetworkRoute: NetworkRoute,
  OracleRoute: OracleRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PayRoute: PayRoute,
  PipelineRoute: PipelineRoute,
  PulseRoute: PulseRoute,
  QuestRoute: QuestRoute,
  QueueRoute: QueueRoute,
  RadarRoute: RadarRoute,
  RelayRoute: RelayRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SellerRoute: SellerRoute,
  SignalRoute: SignalRoute,
  SkillsRoute: SkillsRoute,
  StudioRoute: StudioRoute,
  SyndicateRoute: SyndicateRoute,
  Tier1Route: Tier1Route,
  VaultRoute: VaultRoute,
  WebhooksRoute: WebhooksRoute,
  WhisperRoute: WhisperRoute,
  AgentMerchRoute: AgentMerchRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  WellKnownAgentDotjsonRoute: WellKnownAgentDotjsonRoute,
  ApiAgentCardRoute: ApiAgentCardRoute,
  ApiAgentOrdersRoute: ApiAgentOrdersRouteWithChildren,
  ApiAgentQuoteRoute: ApiAgentQuoteRoute,
  ApiAwsStatusRoute: ApiAwsStatusRoute,
  ApiPayOptionsRoute: ApiPayOptionsRoute,
  ApiPrintifySubscriptionsRoute: ApiPrintifySubscriptionsRoute,
  ApiPrintifySyncRoute: ApiPrintifySyncRoute,
  ApiPrintifyWebhooksRoute: ApiPrintifyWebhooksRoute,
  ApiStoreCatalogRoute: ApiStoreCatalogRoute,
  ApiStoreImageRoute: ApiStoreImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
